version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:tvh25082004@db:5432/qlykho
    volumes:
      - .:/usr/src/app
    command: npm run start:prod

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tvh25082004
      POSTGRES_DB: qlykho
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
