version: '3.8'

services:
  # PostgreSQL service
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tvh25082004
      POSTGRES_DB: dbtest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Your app service (Node.js, NestJS, etc.)
  app:
    build: .
    container_name: your-app
    environment:
      SQL_HOST: postgres
      SQL_PORT: 5432
      SQL_USER: postgres
      SQL_PASSWORD: tvh25082004
      SQL_DB: dbtest
    ports:
      - "3000:3000"  # Adjust to the port your app uses
    depends_on:
      - postgres
    networks:
      - app-network

# Define a network for app communication
networks:
  app-network:
    driver: bridge

# Volumes to persist PostgreSQL data
volumes:
  postgres-data:
