version: "3.7"

services:
  postgresql:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${SQL_DB}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    ports:
      - "${SQL_PORT}:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nestjs:
    build:
      context: .
    environment:
      SQL_DB: qlykho
      SQL_USER: postgres
      SQL_PASSWORD: tvh25082004
      SQL_PORT: 5432
    depends_on:
      - postgresql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
